### ISSUE TITLE
Optimiser le dossier de stockage

### ISSUE THREAD

**Issue by AmauryCarrade** [zDevelopers/i.zcraft.fr#6]
Actuellement, les images sont toutes stockées dans le même dossier (`/static/`).

Je propose de stocker les fichiers dans des sous-dossiers, selon un format classique, mais éprouvé : le fichier `456786458611457687654.jpg` dans `static/45/67/456786458611457687654.jpg`. La miniature au même endroit.
Il faudra adapter les règles de réécriture pour que le fichier reste accessible via http://i.zcraft.fr/456786458611457687654.jpg et http://i.zcraft.fr/mini_456786458611457687654.jpg.

Il faudra également éventuellement modifier la génération du nom afin que le début soit aléatoire (actuellement le début est un hash md5 et la fin le timestamp), afin de mieux répartir les fichiers dans les dossiers.

- [x] Stockage des fichiers
- [x] Génération du nom aléatoire
- [x] Configuration nginx

**Comment by jtremesay** [comment]
Règle nginx à placer dans une directive `server`: `rewrite "^/((mini_)?(\d{2})(\d{2})\d+.(jpeg|jpg|png|gif|tif|tiff))$" "/static/$3/$4/$1" redirect;` (possibilité d'utiliser `permanent` à la place de `redirect`)
